Wisdom_Repository/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin-buku/', include('admin_buku.urls')),
    path('main/', include('daftar_buku.urls')),
    path('', include('authentication_bookmark.urls')),
    path('borrow/', include('pinjam_buku.urls')),
    path('review/', include('review_buku.urls')),
]

admin_buku/urls.py
from django.urls import path
from admin_buku.views import show_main, make_buku, search_books, sort_books, delete_book, request_buku, delete_request_book, get_request_books_json
from admin_buku.views import get_books_json, get_user, get_buku_by_author, book_details, create_book, edit_book, acc_request_book, request_book_details
from admin_buku.views import create_book_flutter, edit_book_flutter, delete_book_flutter, acc_request_book_flutter, delete_request_book_flutter

app_name = 'admin_buku'

urlpatterns = [
    path('', show_main, name='show_main'),

    path('request-book/', request_buku, name='request_book'),
    path('acc-request-book/<int:bookID>/', acc_request_book, name='acc_request_book'),
    path('delete-request-book/<int:bookID>/', delete_request_book, name='delete_request_book'),
    path('request_book_details/', request_book_details, name='request_book_details'),
    path('get-request-books/', get_request_books_json, name='get_request_books_json'),
    

    path('make-book/', make_buku, name='make_book'),
    path('search/', search_books, name='search'),
    path('book_details/', book_details, name='book_details'),
    path('sort/<str:query>', sort_books, name='sort'),

    path('create-book/', create_book, name='create_book'),
    path('edit-book/<int:bookID>/', edit_book, name='edit_book'),
    path('delete-book/<int:bookID>/', delete_book, name='delete_book'),
    
    path('create-book-flutter/', create_book_flutter, name='create_book_flutter'),
    path('edit-book-flutter/', edit_book_flutter, name='edit_book_flutter'),
    path('delete-book-flutter/', delete_book_flutter, name='delete_book_flutter'),
    path('acc-request-book-flutter/', acc_request_book_flutter, name='acc_request_book_flutter'),
    path('delete-request-book-flutter/', delete_request_book_flutter, name='delete_request_book_flutter'),

    path('get-books/', get_books_json, name='get_books_json'),
    path('get_user/', get_user, name='get_user'),
    path('get_buku_by_author/', get_buku_by_author, name='get_buku_by_author'),
]

authentication_bookmark/urls.py
from django.urls import path
from authentication_bookmark.views import show_bookmark
from authentication_bookmark.views import register, get_bookmark_user
from authentication_bookmark.views import login_user, login_flutter, logout_flutter, register_flutter
from authentication_bookmark.views import logout_user, delete_bookmark , add_bookmark_ajax, get_bookmark_json, show_json
from daftar_buku.views import show_main

app_name = 'authentication_bookmark'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('bookmark/', show_bookmark, name='show_bookmark'),
    path('register/', register, name='register'), 
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('delete/<int:id>', delete_bookmark, name='delete_bookmark'),
    path('get-bookmark/', get_bookmark_json, name='get_bookmark_json'),
    path('add-bookmark-ajax/', add_bookmark_ajax, name='add_bookmark_ajax'),
    path('json/', show_json, name='show_json'), 
    path('login-flutter/', login_flutter, name='login'),
    path('logout-flutter/', logout_flutter, name='logout'),
    path('register-flutter/', register_flutter, name = 'register'),
    path('get_bookmark_user/', get_bookmark_user, name='get_bookmark_user'),
]

daftar_buku/urls.py
from django.urls import path
from daftar_buku.views import show_main, make_buku, book_details, search_books, sort_books, show_xml, get_books_json, get_user, get_buku_by_author, create_request_book, get_buku_search, sort_books_json,\
sort_books_json, get_rating


app_name = 'daftar_buku'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('make-book/', make_buku, name='make_book'),
    path('book_details/', book_details, name='book_details'),
    path('search/', search_books, name='search'),
    path('sort/<str:query>', sort_books, name='sort'),
    path('xml/<int:id>/', show_xml, name='show_xml'),
    path('get_books_json/', get_books_json, name='get_books_json'),
    path('get_user/', get_user, name='get_user'),
    path('get_buku_by_author/', get_buku_by_author, name='get_buku_by_author'),
    path('create-request-book/', create_request_book, name='create_request_book'),
    path('searchjson/', get_buku_search, name='get_buku_search'),
    path('sortjson/<str:query>', sort_books_json, name='sort_books_json'),
    path('get_rating/', get_rating, name='get_rating'),
    
]

daftar_buku/models.py
from django.db import models

# Create your models here.

#make model books in accordance with books.csv
class Buku(models.Model):
    isbn = models.CharField(max_length=20)
    judul = models.CharField(max_length=100)
    penulis = models.CharField(max_length=100)
    tahun = models.IntegerField()
    kategori = models.CharField(max_length=100)
    gambar = models.CharField(max_length=100)
    deskripsi = models.TextField()
    rating = models.ForeignKey('Rating', on_delete=models.CASCADE, default=0)
    def __str__(self):
        return self.judul
    def __unicode__(self):
        return self.judul
    
class Rating(models.Model):
    rating = models.DecimalField(max_digits=5, decimal_places=2)

daftar_buku/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField(label='Cari', max_length=100)  

daftar_buku/views.py
from django.shortcuts import render
from daftar_buku.models import Buku, Rating
import pandas
import os
from django.http import HttpResponseRedirect, HttpResponseNotFound
from django.urls import reverse
from django.core.paginator import Paginator, Page
from django.http import JsonResponse
from django.db.models import Q
from django.db import transaction
from django.core.paginator import EmptyPage, PageNotAnInteger
from django.db.models.functions import Lower
from .forms import SearchForm
from django.core import serializers
from django.http import HttpResponse
#import session
from django.contrib.sessions.models import Session
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_exempt
from admin_buku.models import RequestBuku
import json

daftar_genre = [
        "Fiction",
        "Juvenile Fiction",
        "Biography & Autobiography",
        "History",
        "Literary Criticism",
        "Philosophy",
        "Comics & Graphic Novels",
        "Religion",
        "Drama",
        "Juvenile Nonfiction",
    ]

@require_http_methods(["GET", "POST"])
@csrf_exempt
def search_books(request):
    
    if not request.method == 'POST':
        if 'search-books' in request.session:
            if 'search-books' in request.session:
                request.POST = request.session['search-books']
            request.method = 'POST'

    if request.method == 'POST':
        form = SearchForm(request.POST)
        request.session['search-books'] = request.POST

        if form.is_valid():
            query = form.cleaned_data['query']
            buku_list = Buku.objects.filter(Q(judul__icontains=query) | Q(penulis__icontains=query) | Q(kategori__icontains=query))

            paginator = Paginator(buku_list, 24)
            page = request.GET.get('page', 1)

            try:
                buku_list = paginator.page(page)
            except PageNotAnInteger:
                buku_list = paginator.page(1)
            except EmptyPage:
                buku_list = paginator.page(paginator.num_pages)

            print(request)

            try:
                tipe = request.user.member
            except:
                tipe = 'guest'
            context = {
                'buku': buku_list,
                'genre' : daftar_genre,
                'tipe' : tipe,
            }

            return render(request, 'main.html', context)

        else:
            return render(request, 'main.html', {'form': form})

@csrf_exempt
def get_rating(request):

    rating_list = Rating.objects.all()
    rating_list_json = serializers.serialize('json', rating_list)
    return HttpResponse(rating_list_json)

@csrf_exempt
def get_buku_search(request):

    if request.method == 'POST':
        form = request.POST.get('query')
        buku = Buku.objects.filter(Q(judul__icontains=form) | Q(penulis__icontains=form) | Q(kategori__icontains=form))
        buku_list_json = serializers.serialize('json', buku)
        return HttpResponse(buku_list_json)
    
@csrf_exempt    
def sort_books_json(request, query):
    
    if query == 'judul':
        buku = Buku.objects.all().order_by(Lower('judul'))
    elif query == 'tahun':
        buku = Buku.objects.all().order_by('tahun')
    elif query == 'rating':
        buku = Buku.objects.all().order_by('-rating__rating')
    buku_list_json = serializers.serialize('json', buku)
    
    return HttpResponse(buku_list_json)

   

@csrf_exempt
def get_buku_by_author(request):

    if request.method == 'POST':
        form = request.POST.get('query')
        buku = Buku.objects.filter(Q(penulis__icontains=form))
        buku_list_json = serializers.serialize('json', buku)
        return HttpResponse(buku_list_json)
    
def sort_books(request, query):
   
    if request.method == 'GET':

        sort = request.GET.getlist('Sort', request.session.get('Sort'))
        buku_list = Buku.objects.all()
        if query == 'judul':
            buku_list = buku_list.order_by(Lower('judul'))
        if query == 'tahun':
            buku_list = buku_list.order_by('tahun')
        if query == 'rating':
            buku_list = buku_list.order_by('-rating__rating')
        paginator = Paginator(buku_list, 24)  
        page = request.GET.get('page')
        buku = paginator.get_page(page)
        try:
            tipe = request.user.member
        except:
            tipe = 'guest'
        context = {
            'buku': buku,
            'genre' : daftar_genre,
            'tipe' : tipe,
        }
        request.session['Sort'] = sort
        return render(request, 'main.html', context)

  

def book_details(request):

    book_id = request.GET.get('id')
    book = Buku.objects.get(id=book_id)
    try:
        if request.user.member == 'regular' or request.user.member == 'premium':
            deskripsi = book.deskripsi
        else:
            deskripsi = "kamu perlu login dulu untuk melihat deskripsi buku ini"
    except:
        deskripsi = "kamu perlu login dulu untuk melihat deskripsi buku ini"
    return JsonResponse({'judul': book.judul,
                        'penulis': book.penulis,
                        'tahun': book.tahun,
                        'kategori': book.kategori,
                        'gambar': book.gambar,
                        'deskripsi':deskripsi,})


def make_buku(request):

    file_path = os.path.join(os.path.dirname(__file__), 'static/books.csv')
    file_csv = open(file_path, 'r', encoding='utf-8')
    data = pandas.read_csv(file_csv, encoding='utf-8')

    buku = {}
    buku['isbn'] = data['isbn13'].tolist()
    buku['judul'] = data['title'].tolist()
    buku['penulis'] = data['authors'].tolist()
    buku['tahun'] = data['published_year'].tolist()
    buku['kategori'] = data['categories'].tolist()
    buku['gambar'] = data['thumbnail'].tolist()
    buku['deskripsi'] = data['description'].tolist()
    buku['rating'] = data['average_rating'].tolist()

    counter = 0

    with transaction.atomic():
        for i in range(0, len(data['isbn13'])):
            try:
                if counter == 100:
                    break
                rating_obj = Rating(rating=buku['rating'][i])
                rating_obj.save()

                rating = Rating.objects.get(pk=rating_obj.pk)
                buku_obj = Buku(isbn=buku['isbn'][i], judul=buku['judul'][i], penulis=buku['penulis'][i], tahun=buku['tahun'][i], kategori=buku['kategori'][i], gambar=buku['gambar'][i], deskripsi=buku['deskripsi'][i], rating=rating)
                buku_obj.save()
                counter += 1
            except:
                print("tesss")
                pass

    return HttpResponseRedirect(reverse('daftar_buku:show_main'))

def show_xml(request, id):
    data = Buku.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")


def show_main(request):

    if(len(Buku.objects.all()) == 0):
        make_buku(request)    
    buku_list = Buku.objects.all()
    paginator = Paginator(buku_list, 24)  
    page = request.GET.get('page')
    buku = paginator.get_page(page)
    try:
        tipe = request.user.member
    except:
        tipe = 'guest'
    context = {
        'buku': buku,
        'genre' : daftar_genre,
        'tipe' : tipe,
    }
    return render(request, 'main.html', context)

def sort(request, query):
        if query == 'judul':
            buku_list = Buku.objects.all().order_by(Lower('judul'))
        elif query == 'tahun':
            buku_list = Buku.objects.all().order_by('tahun')
        elif query == 'rating':
            buku_list = Buku.objects.all().order_by('-rating__rating')
        else:
            buku_list = Buku.objects.all()
        paginator = Paginator(buku_list, 24)  
        page = request.GET.get('page')
        buku = paginator.get_page(page)
        context = {
            'buku': buku,
            'genre': daftar_genre,
        }
        return render(request, 'main.html', context)
    
@csrf_exempt
def get_books_json(request):
    buku_list = Buku.objects.all()
    buku_list_json = serializers.serialize('json', buku_list)
    print(buku_list[11].rating.rating)
    return HttpResponse(buku_list_json)


def get_user(request):
    if request.user.is_authenticated:
        return JsonResponse({'username': request.user.username})
    else:
        return JsonResponse({'username': 'Anonymous'})

@csrf_exempt
def create_request_book(request):
    if request.method == 'POST':
        isbn = request.POST.get('isbn', '')
        judul = request.POST.get('judul', '')
        penulis = request.POST.get('penulis', '')
        tahun = request.POST.get('tahun', 0)  
        kategori = request.POST.get('kategori', '')
        gambar = request.POST.get('gambar', '')
        deskripsi = request.POST.get('deskripsi', '')
        rating_obj = Rating(rating=request.POST.get('rating', 0.0))
        rating_obj.save()

        rating = Rating.objects.get(pk=rating_obj.pk)

        buku = RequestBuku(
            isbn=isbn,
            judul=judul,
            penulis=penulis,
            tahun=tahun,
            kategori=kategori,
            gambar=gambar,
            deskripsi=deskripsi,
            rating=rating,
            user=request.user,
        )

        buku.save()

        return HttpResponse(b"CREATED", status=201)
    
    return HttpResponseNotFound()

daftar_buku/templates/navbar.html
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/5.3.2/jquery.min.js"></script>
</head>

<nav class="navbar navbar-expand-lg navbar-light navbar-custom">
    <a class="navbar-brand" href="{% url 'daftar_buku:show_main' %}">
        <img src="https://raw.githubusercontent.com/PBP-D-11-2023/Wisdom-Repository/anisha/assets/images/wr%20logo.png"
                    alt="Logo" width="156" height="52" class="d-inline-block align-text-top">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mx-auto">
            <li class="nav-item d-flex align-items-center">
                <form method="post" action="{% url 'daftar_buku:search'%}" class="form-inline">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="search" name="query" placeholder="Cari..." aria-describedby="button-addon">
                        <div class="input-group-append">
                            <button id="cariUtama" type="submit" class="btn btn-primary" id="button-addon">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </li>
        </ul>
        <ul class="navbar-nav" id="navbarNav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'authentication_bookmark:login' %}">Login</a>
            </li>
        </ul>
    </div>
</nav>




<style>
        .navbar-brand{
            margin: 0;
            text-align: center;
            padding: 10px;
            display: flex;
            justify-content: space-between;
            align-items: center;


        }
        .navbar-custom {
            background-color: white; 
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            height: 120px;
        }

        .input-group {
            display: flex;
            justify-content: center;
            align-items: center;
            margin: 0 auto;
        }

        .form-inline {
            background-color:  #e1e1e1 !important;
            display: flex;   
            text-align: center;
            justify-content: center;
            align-items: center; 
            
        }

        .form-control {
            background-color:  #e1e1e1!important; 
            color: #fff !important; 
            margin-left: auto !important;
            margin-right: auto !important;
        }

        form {
            color: black;
            display: flex;
            padding: 2px;
            border-radius: 50px;
            margin: 0 0 10px;
            

        }

      

        input[type="search"] {
            color: #000000;
            border: none;
            background: transparent;
            margin: 0;
            padding: 10px 130px 10px 0px;;
            font-size: 14px;
            color: inherit;
            border: 1px solid transparent;
            border-radius: 10px;
            padding-left: 30px; 
        }

        input[type="search"]::placeholder {
            color: #000000;
        }

        #cariUtama {
            text-indent: -999px;
            overflow: hidden;
            width: 40px;
            padding: 0;
            margin: 0;
            border: 1px solid transparent;
            border-radius: inherit;
            background: transparent url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' class='bi bi-search' viewBox='0 0 16 16'%3E%3Cpath d='M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z' fill='black'%3E%3C/path%3E%3C/svg%3E") no-repeat center;
            cursor: pointer;
            opacity: 0.7;
            
        }

        #cariUtama:hover {
            opacity: 1;
        }

        #cariUtama:focus,
            input[type="search"]:focus {
            box-shadow: 0 0 3px 0 ;
            outline: none;
        }

        .navbar-nav {
            display: flex;
            align-items: center;
        }

        .navbar-toggler {
            display: none; 
        }

        @media (max-width: 768px) {
            .navbar-toggler {
                display: block;
            }


            .navbar-nav {
                flex-direction: column;
                align-items: flex-start;
            }

            .navbar-nav .nav-link {
                padding: 5px 15px;
            }

            .navbar-nav.show {
                display: flex;
            }
        }




</style>

daftar_buku/templates/search.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>

<body>
    {% include "navbar.html" %}
    <div class="container">
        <h1>List of Books</h1>
  
        <a href="{% url 'daftar_buku:show_main' %}">Home</a>

        <div id="book_container" class="row">
            <!-- Your book cards are rendered here -->
        </div>
        <form method="post" action="{% url 'daftar_buku:search' %}" id="search-form">
            {% csrf_token %}
            <input type="text" name="query" id="search-input" placeholder="Cari...">
            <button type="submit" class="btn btn-primary" id="search-button">Cari</button>
        </form>

        <div class="modal fade" id="bookModal" tabindex="-1" aria-labelledby="bookModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="bookModalLabel">Detail Buku</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <h5>Judul:</h5>
                        <p id="book-title"></p>
                        <h5>Penulis:</h5>
                        <p id="book-author"></p>
                        <h5>Rating:</h5>
                        <p id="book-rating"></p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="pagination">
            <span class="step-links">
            {% if buku.has_previous %}
                <a href="?page=1" id="first-page">&laquo; first</a>
                <a href="?page={{ buku.previous_page_number }}" id="previous-page">previous</a>
            {% endif %}

            <span class="current-page">
                Page {{ buku.number }} of {{ buku.paginator.num_pages }}.
            </span>

            {% if buku.has_next %}
                <a href="?page={{ buku.next_page_number }}" id="next-page">next</a>
                <a href="?page={{ buku.paginator.num_pages }}" id="last-page">last &raquo;</a>
            {% endif %}
            </span>
        </div>
    </div>

    <script>
        $(document).on('click', '.show-details', function() {
            var bookId = $(this).data("id");
            $.ajax({
                url: "{% url 'daftar_buku:book_details' %}",
                method: "GET",
                data: { id: bookId },
                success: function(data) {
                    $("#book-title").text("Judul: " + data.judul);
                    $("#book-author").text("Penulis: " + data.penulis);
                },
            });
        });

        fetch('{% url "daftar_buku:show_main" %}')
            .then(response => response.text())
            .then(data => {
                const tempDiv = document.createElement('div');
                tempDiv.innerHTML = data;
                const navbarStyle = tempDiv.querySelector('#navbar-css').textContent;

                const styleElement = document.createElement('style');
                styleElement.textContent = navbarStyle;
                document.head.appendChild(styleElement);

                const navbarElement = tempDiv.querySelector('.navbar');
                if (navbarElement) {
                    document.getElementById('navbar-container').appendChild(navbarElement);
                }
            });

        async function getBooks() {
            return fetch("{% url 'daftar_buku:get_books_json' %}").then((res) => res.json());
        }

        async function refreshBooks() {
            const books = await getBooks();

            // Clear the existing book cards
            const bookContainer = document.getElementById("book_container");
            bookContainer.innerHTML = "";

            books.forEach((book) => {
                const card = document.createElement("div");
                card.className = "col-md-2 card small-card";

                const image = document.createElement("img");
                image.className = "card-img";
                image.src = book.fields.gambar;
                image.alt = book.fields.judul;

                const cardBody = document.createElement("div");
                cardBody.className = "card-body d-flex flex-column";

                const cardTitle = document.createElement("h5");
                cardTitle.className = "card-title";
                cardTitle.style = "white-space: nowrap; overflow: hidden; text-overflow: ellipsis;";
                cardTitle.title = book.fields.judul;
                cardTitle.innerText = book.fields.judul;

                const detailButton = document.createElement("button");
                detailButton.type = "button";
                detailButton.className = "btn btn-primary show-details";
                detailButton.setAttribute("data-bs-toggle", "modal");
                detailButton.setAttribute("data-bs-target", "#bookModal");
                detailButton.setAttribute("data-id", book.id);
                detailButton.innerText = "Detail";

                cardBody.appendChild(cardTitle);
                cardBody.appendChild(detailButton);

                card.appendChild(image);
                card.appendChild(cardBody);

                bookContainer.appendChild(card);
            });
        }

        // Call the refreshBooks function to initially populate the book cards
        refreshBooks();

        

        
    </script>

    <style>
        .card-img {
            width: 100%; 
            height: 600px;
            object-fit: cover;
        }
        .small-card {
            max-width: 10rem;
            height: 22rem;
        }

        .small-card .card {
            height: 100%;
            margin: 0;
            padding: 0;
        }

        .small-card .card-img {
            max-width: 100%; 
            height: 60%; 
            object-fit: cover; 
        }

        .small-card .card-title {
            font-size: 14px; 
        }

        .small-card .card-body {
            height: 40%;
        }

        
        

    </style>
</body>
</html>