Wisdom_Repository/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin-buku/', include('admin_buku.urls')),
    path('main/', include('daftar_buku.urls')),
    path('', include('authentication_bookmark.urls')),
    path('borrow/', include('pinjam_buku.urls')),
    path('review/', include('review_buku.urls')),
]

admin_buku/urls.py
from django.urls import path
from admin_buku.views import show_main, make_buku, search_books, sort_books, delete_book, request_buku, delete_request_book, get_request_books_json
from admin_buku.views import get_books_json, get_user, get_buku_by_author, book_details, create_book, edit_book, acc_request_book, request_book_details
from admin_buku.views import create_book_flutter, edit_book_flutter, delete_book_flutter, acc_request_book_flutter, delete_request_book_flutter

app_name = 'admin_buku'

urlpatterns = [
    path('', show_main, name='show_main'),

    path('request-book/', request_buku, name='request_book'),
    path('acc-request-book/<int:bookID>/', acc_request_book, name='acc_request_book'),
    path('delete-request-book/<int:bookID>/', delete_request_book, name='delete_request_book'),
    path('request_book_details/', request_book_details, name='request_book_details'),
    path('get-request-books/', get_request_books_json, name='get_request_books_json'),
    

    path('make-book/', make_buku, name='make_book'),
    path('search/', search_books, name='search'),
    path('book_details/', book_details, name='book_details'),
    path('sort/<str:query>', sort_books, name='sort'),

    path('create-book/', create_book, name='create_book'),
    path('edit-book/<int:bookID>/', edit_book, name='edit_book'),
    path('delete-book/<int:bookID>/', delete_book, name='delete_book'),
    
    path('create-book-flutter/', create_book_flutter, name='create_book_flutter'),
    path('edit-book-flutter/', edit_book_flutter, name='edit_book_flutter'),
    path('delete-book-flutter/', delete_book_flutter, name='delete_book_flutter'),
    path('acc-request-book-flutter/', acc_request_book_flutter, name='acc_request_book_flutter'),
    path('delete-request-book-flutter/', delete_request_book_flutter, name='delete_request_book_flutter'),

    path('get-books/', get_books_json, name='get_books_json'),
    path('get_user/', get_user, name='get_user'),
    path('get_buku_by_author/', get_buku_by_author, name='get_buku_by_author'),
]

authentication_bookmark/urls.py
from django.urls import path
from authentication_bookmark.views import show_bookmark
from authentication_bookmark.views import register, get_bookmark_user
from authentication_bookmark.views import login_user, login_flutter, logout_flutter, register_flutter
from authentication_bookmark.views import logout_user, delete_bookmark , add_bookmark_ajax, get_bookmark_json, show_json
from daftar_buku.views import show_main

app_name = 'authentication_bookmark'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('bookmark/', show_bookmark, name='show_bookmark'),
    path('register/', register, name='register'), 
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('delete/<int:id>', delete_bookmark, name='delete_bookmark'),
    path('get-bookmark/', get_bookmark_json, name='get_bookmark_json'),
    path('add-bookmark-ajax/', add_bookmark_ajax, name='add_bookmark_ajax'),
    path('json/', show_json, name='show_json'), 
    path('login-flutter/', login_flutter, name='login'),
    path('logout-flutter/', logout_flutter, name='logout'),
    path('register-flutter/', register_flutter, name = 'register'),
    path('get_bookmark_user/', get_bookmark_user, name='get_bookmark_user'),
]

pinjam_buku/urls.py
from django.urls import path
from pinjam_buku.views import pinjam_buku_outer, lihatbukudipinjam, get_peminjaman_json, get_peminjaman_json_by_id, pengembalian_by_ajax, show_pengembalian

app_name = 'pinjam_buku'

urlpatterns = [
    path('details/<int:id>/', pinjam_buku_outer, name='pinjam_buku'),
    path('borrowed/', lihatbukudipinjam, name="list_pinjam"),
    path('peminjamanjson/', get_peminjaman_json, name="get_peminjaman_json"),
    path('peminjamanjsonbyid/<int:id>', get_peminjaman_json_by_id, name="get_peminjaman_json_by_id"),
    path('pengembalianbyajax', pengembalian_by_ajax, name="pengembalian_ajax"),
    path('returned/', show_pengembalian, name="show_pengembalian"),
]

authentication_bookmark/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import Group, Permission
from django.db import models
from daftar_buku.models import Buku

class CustomUser(AbstractUser):
    member = models.CharField(
        max_length=20,
        choices=[
            ('regular', 'Regular'),
            ('premium', 'Premium')
        ],
        default='regular'
    )

    groups = models.ManyToManyField(Group, related_name='custom_users_groups')
    user_permissions = models.ManyToManyField(Permission, related_name='custom_users_permissions')

class Bookmark(models.Model):
    buku = models.ForeignKey(Buku, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    judul = models.CharField(max_length=100, default='default')
    gambar = models.CharField(max_length=100, default='default')

authentication_bookmark/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import CustomUser

class SignupForm(UserCreationForm):
    member = forms.ChoiceField(
        widget=forms.RadioSelect,
        choices=[
            ('regular', 'Regular'),
            ('premium', 'Premium')
        ],
        initial='regular'
    )

    class Meta:
        model = CustomUser
        fields = ('username', 'member')

authentication_bookmark/views.py
import json
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.contrib import messages  
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login as auth_login
from django.http import JsonResponse
from django.contrib.auth import logout as auth_logout
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib import messages  
from django.contrib.auth.decorators import login_required
from .forms import SignupForm
from django.views.decorators.csrf import csrf_exempt
from authentication_bookmark.models import Bookmark
from django.core import serializers
from daftar_buku.models import Buku

# Create your views here.
@login_required(login_url='/login')
def show_bookmark(request):
    bookmarks = Bookmark.objects.filter(user=request.user)
    data = Buku.objects.all()    
    context = {
        'name': request.user.username,
        'member' : request.user.member,
        'bookmarks': bookmarks,
        'data' : data,
    }

    return render(request, "bookmark.html", context)

def register(request):
    form = SignupForm()

    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('authentication_bookmark:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if user.is_superuser:
                response = HttpResponseRedirect(reverse('admin_buku:show_main')) 
            else:
                response = HttpResponseRedirect(reverse('daftar_buku:show_main')) 
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    return redirect('daftar_buku:show_main')

@csrf_exempt
def add_bookmark_ajax(request):
    if request.method == 'GET':
        id_buku = request.GET.get('id_buku')
        buku = Buku.objects.get(pk=id_buku)
        user = request.user

        # Periksa apakah buku sudah ada di bookmark user
        existing_bookmark = Bookmark.objects.filter(buku=buku, user=user)
        if existing_bookmark.exists():
            # Jika sudah ada, kirim pesan bahwa buku sudah ada di bookmark
            return JsonResponse({'message': 'Buku sudah ada di bookmark'}, status=201)

        # Jika belum ada, tambahkan ke bookmark
        new_bookmark = Bookmark(buku=buku, user=user, judul=buku.judul, gambar=buku.gambar)
        new_bookmark.save()
        return JsonResponse({'message': 'Bookmark berhasil ditambahkan'}, status=201)

    return JsonResponse({'message': 'Metode tidak diizinkan'}, status=405)
 
def get_bookmark_json(request):
    bookmark_item = Bookmark.objects.all()
    return HttpResponse(serializers.serialize('json', bookmark_item))
@csrf_exempt
def get_bookmark_user(request):
    bookmark_user = Bookmark.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", bookmark_user), content_type="application/json")

def show_json(request):
    data = Bookmark.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def delete_bookmark(request, id):
    # Get data berdasarkan ID
    buku = Bookmark.objects.get(pk = id)
    # Hapus data
    buku.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('authentication_bookmark:show_bookmark'))

@csrf_exempt
def login_flutter(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            auth_login(request, user)
            if user.is_superuser:
                tipe = "admin"
            else:
                tipe = "biasa"
            # Status login sukses.
            return JsonResponse({
                "username": user.username,
                "status": True,
                "member": user.member,
                "tipe": tipe,
                "message": "Login sukses!"
            }, status=200)
        else:
            return JsonResponse({
                "status": False,
                "message": "Login gagal, akun dinonaktifkan."
            }, status=401)

    else:
        return JsonResponse({
            "status": False,
            "message": "Login gagal, periksa kembali email atau kata sandi."
        }, status=401)

@csrf_exempt
def logout_flutter(request):
    username = request.user.username
    try:
        auth_logout(request)
        return JsonResponse({
            "username": username,
            "status": True,
            "message": "Logout berhasil!"
        }, status=200)
    except:
        return JsonResponse({
        "status": False,
        "message": "Logout gagal."
        }, status=401)

@csrf_exempt
def register_flutter(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return JsonResponse({
                "status": True,
                "message": "Registrasi berhasil!"
            }, status=200)
        else:
            errors = form.errors.get_json_data(escape_html=False)  # Mendapatkan pesan kesalahan form
            return JsonResponse({
                "status": False,
                "errors": errors,
                "message": "Registrasi gagal, silakan perbaiki data yang dimasukkan."
            }, status=400)
    else:
        return JsonResponse({
            "status": False,
            "message": "Registrasi gagal, metode request tidak valid."
        }, status=405)

authentication_bookmark/templates/bookmark.html
{% extends 'base.html' %}

{% block content %}

{% include 'navbaruser.html' %}
{% load static %}

<style>
    body {
        background-color: #F5F2ED;
        background-repeat: no-repeat;
        font-family: 'Baskerville Regular', Baskerville;
    }
    h1 {
        font-size: 70px;
        text-align: center;
        padding-top: 50px; 
        padding-left: 30px;
        top: auto;
        color: #37465D;
    }
    p {
        color: #37465D;
        font-size: 30px; /* Added 'px' */
    }

    .header{
        position: absolute;
        top: 30%; /* Pusatkan header secara vertikal */
        left: 50%; /* Pusatkan header secara horizontal */
        transform: translate(-50%, -50%); /* Koreksi posisi untuk menjaga header di tengah */
        display: flex;
        align-items: center;
    }

    .header img{
        width: 70px;
        height: 70px;
        box-shadow: none;
    }

    p{
        padding-left: 50px;
    }

    .backimg{
        padding-top: 78px;
    }
    .imgbuku {
        max-width: 100%; /* Ensure the image doesn't exceed the card width */
        width: 130px;
        height: 200px;
        display: block; /* Remove any extra space around the image */
        margin: 0 auto; /* Center the image horizontally */
        padding: 10;
        border-radius: 5px;
        box-shadow: 0 0 3px 5px rgba(209, 209, 209, 0.3);
    }

    .mark{
        position: absolute;
        background: transparent;
        top: 5px; /* Adjust as needed for positioning */
        right: 5px; /* Adjust as needed for positioning */
        width: 40px; /* Adjust the size of the 'bookmark' icon */
        height: 35px; /* Adjust the size of the 'bookmark' icon */
        box-shadow: none;
    }

    .card button {
        padding: 3px 5px;
        font-size: 14px;
        text-align: center;
        cursor: pointer;
        outline: none;
        color: #fff;
        border: none;
        border-radius: 5px;
        box-shadow: 0 4px #c7c7c7;
    }

    .card button:hover {background-color: #f5d41a}

    .card button:active {
        box-shadow: 0 1px #c7c7c7;
        transform: translateY(4px);
    }

    .deletebutton{
        background-color: rgb(255, 97, 97);
    }

    .pinjambutton{
        padding: 3px 5px;
        font-size: 14px;
        text-align: center;
        cursor: pointer;
        outline: none;
        color: #fff;
        background-color: rgb(65, 194, 119);
        border: none;
        border-radius: 5px;
        box-shadow: 0 4px #c7c7c7;
    }
    
    .delete{
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
    }

    .delete > * {
        margin: 2px; /* Menambahkan jarak 10px di sekitar setiap elemen di dalam .delete */
    }
    .delete img{
        width: 20px;
        height: 20px;
    }

    .card{
        box-shadow: 0 0 3px 5px rgba(209, 209, 209, 0.3);
        align-items: center;
        width: fit-content;
        height: fit-content;
        margin: 10px; /* Adding margin between cards */
        padding: 10px; /* Fixing the padding unit */
    }

    h3{
        font-size: 15px;
        align-items: center;
        font-weight: bold;
        color: #37465D;
    }

    .card-container {
        display: flex;
        flex-wrap: wrap;
        justify-content: center; /* Align cards in the center horizontally */
        margin: 30;
    }

    .user {
        display: flex;
        justify-content: space-between;
        padding: 10px;
        padding-right: 20px;
    }

    .member{
        display: flex;
        color: #37465D;
        text-transform: capitalize;
        vertical-align: sub;
    }
    .member img{
        width: 20px;
        height: 20px;
    }

</style>

<div class="header">
    <img src="https://www.iconsdb.com/icons/preview/color/37465D/bookmark-5-xxl.png">
    <h1>Bookmark</h1>
</div>
<img class='backimg' src="https://raw.githubusercontent.com/PBP-D-11-2023/Wisdom-Repository/anisha/assets/images/bookmark.png">

<div class="user">
    <p>Hey, {{ name }}!</p>
    <div class="member">
        <img src="{% static 'authentication_bookmark/img/user.png' %} ">
        <h5>{{ member }}</h5>
    </div>
</div>
{% csrf_token %}
<p><u>List of Books:</u></p>
<div class="container">
    <div class="card-container" id="product-table"></div>
</div>

<script>
    async function getProducts() {
        return fetch("{% url 'authentication_bookmark:get_bookmark_json' %}").then((res) => res.json());
    }

    async function refreshProducts() {
        const productsContainer = document.getElementById("product-table");
        productsContainer.innerHTML = ""; // Clear the container before appending new items
        const products = await getProducts();

        products.forEach((item) => {
            const pinjamLink = "{% url 'pinjam_buku:pinjam_buku' 0 %}".replace('0', item.fields.buku);
            const card = `
                <div class="card" data-product-id="${item.pk}">
                    <img class= 'mark' src="https://www.iconsdb.com/icons/preview/color/37465D/bookmark-5-xxl.png">
                    <img class = 'imgbuku' src="${item.fields.gambar}">
                    <h3>${item.fields.judul}</h3>

                    <div class="delete">
                        <img src=https://www.iconsdb.com/icons/preview/red/delete-xxl.png>
                        <button class='deletebutton' onclick="deleteItem(${item.pk})">Delete</button>
                        <a class='pinjambutton' href="${pinjamLink}">Pinjam</a>
                    </div>
                </div>
            
            `;
            productsContainer.insertAdjacentHTML("beforeend", card);
        });
    }

    async function deleteItem(id) {
        try {
            const csrftoken = document.querySelector('input[name="csrfmiddlewaretoken"]').value;

            const response = await fetch(`/delete/${id}`, {
                method: 'DELETE',
                headers: {
                    'X-CSRFToken': csrftoken,
                },
            });
            refreshProducts();
            if (response.ok) {
                const data = await response.json();
                console.log('Delete request successful', data);
                refreshProducts();
            } else {
                console.error('Delete request failed:', response.status);
            }
        } catch (error) {
            console.error('Error:', error);
        }
    }


    refreshProducts();
</script>
{% endblock content %}

authentication_bookmark/templates/login.html
{% extends 'base.html' %}
{% block meta %}
    <title>Login</title>
{% endblock meta %}
{% block content %}
<style>
    section {
        background-image: url(https://github.com/PBP-D-11-2023/Wisdom-Repository/raw/anisha/assets/images/login.png);
        background-size: cover; /* Untuk mengisi seluruh area section */
        background-position: center center; /* Untuk posisi tengah secara horizontal dan vertikal */
        background-repeat: no-repeat; /* Agar gambar latar belakang tidak diulang */
        height: 100vh; /* Mengatur tinggi section sejajar dengan tinggi tampilan (viewport height) */
    }

    .card {
        font-family: 'Baskerville Regular', Baskerville;
        width: 400px; /* Lebar form login */
        background-color: #37465D;
        margin: 0 auto; /* Mengatur margin otomatis pada sisi kiri dan kanan, membuat form berada di tengah */
        padding: 20px; /* Ruang dalam form login */
        text-align: center; /* Teks berada di tengah form login */
        border-radius: 3%;
        color: white; /* Mengatur warna teks menjadi putih */
        position: absolute;
        transform: translate(-50%,-50%);
        top: 50%;
        left: 50%;
    }

    img{
        width: 150px;
    }

    input{
        font-family: 'Baskerville Regular', Baskerville;
    }
    a{
        color: wheat;
    }
</style>


<body>
    <section>
        <div class="hero-body has-text-centered is-flex is-justify-content-center is-align-items-center" >
            <div class="card">
                <div class="card-content">
                <div class="login">
                    <img src="https://github.com/PBP-D-11-2023/Wisdom-Repository/raw/anisha/assets/images/logo%20wr%20putih.png" height= "60px" width="180px" style="padding-bottom: 20px;">
                    <form method="POST" action="">
                    {% csrf_token %}
                    <div class="field">
                        <div class="control">
                        <input class="input is-medium is-rounded" type="text" name="username" placeholder="Username" autocomplete="username" required />
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                        <input class="input is-medium is-rounded" type="password" name="password" placeholder="Password" autocomplete="current-password" required />
                        </div>
                    </div>
                    <br />
                    <button class="button is-block is-fullwidth is-primary is-medium is-rounded" type="submit" value="Login">
                        Login
                    </button>
                    </form>
                    {% if messages %}
                    <ul>
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}     
                    <br>
                    <nav class="level">
                    <div class="level-item has-text-centered">
                        <div>
                            Don't have an account yet? <a href="{% url 'authentication_bookmark:register' %}">Register Now</a>
                        </div>
                    </div>
                    </nav>
                </div>
                </div>
            </div>
        </div>
    </section>
</body>

{% endblock content %}

authentication_bookmark/templates/register.html
{% extends 'base.html' %}
{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  
<style>
    section {
        background-image: url(https://github.com/PBP-D-11-2023/Wisdom-Repository/raw/anisha/assets/images/login.png);
        background-size: cover; /* Untuk mengisi seluruh area section */
        background-position: center center; /* Untuk posisi tengah secara horizontal dan vertikal */
        background-repeat: no-repeat; /* Agar gambar latar belakang tidak diulang */
        height: 100vh; /* Mengatur tinggi section sejajar dengan tinggi tampilan (viewport height) */
    }

    .register {
        font-family: 'Baskerville Regular', Baskerville;
        width: 600px; /* Lebar form login */
        background-color: #37465D;
        margin: 0 auto; /* Mengatur margin otomatis pada sisi kiri dan kanan, membuat form berada di tengah */
        padding: 20px; /* Ruang dalam form login */
        text-align: center; /* Teks berada di tengah form login */
        border-radius: 3%;
        color: white; /* Mengatur warna teks menjadi putih */
        position: absolute;
        transform: translate(-50%,-50%);
        top: 50%;
        left: 50%;
    }

    table{
        color: white;
    }

    input{
        font-family: 'Baskerville Regular', Baskerville;
    }
    a{
        color: wheat;
    }
    img{
        width: 150px;
    }
</style>
<section>

    <div class = "register">
        <img src="https://github.com/PBP-D-11-2023/Wisdom-Repository/raw/anisha/assets/images/logo%20wr%20putih.png" height= "60px" width="180px" style="padding-bottom: 20px;">
            <form method="POST" >  
                {% csrf_token %}  
                <table>  
                    {{ form.as_table }}  
                    <tr>  
                        <td></td>
                        <td><input type="submit" name="submit" value="Daftar"/></td>  
                    </tr>  
                </table>  
            </form>

        {% if messages %}  
            <ul>   
                {% for message in messages %}  
                    <li>{{ message }}</li>  
                    {% endfor %}  
            </ul>   
        {% endif %}

    </div>  
</section>
{% endblock content %}