Wisdom_Repository/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin-buku/', include('admin_buku.urls')),
    path('main/', include('daftar_buku.urls')),
    path('', include('authentication_bookmark.urls')),
    path('borrow/', include('pinjam_buku.urls')),
    path('review/', include('review_buku.urls')),
]

admin_buku/urls.py
from django.urls import path
from admin_buku.views import show_main, make_buku, search_books, sort_books, delete_book, request_buku, delete_request_book, get_request_books_json
from admin_buku.views import get_books_json, get_user, get_buku_by_author, book_details, create_book, edit_book, acc_request_book, request_book_details
from admin_buku.views import create_book_flutter, edit_book_flutter, delete_book_flutter, acc_request_book_flutter, delete_request_book_flutter

app_name = 'admin_buku'

urlpatterns = [
    path('', show_main, name='show_main'),

    path('request-book/', request_buku, name='request_book'),
    path('acc-request-book/<int:bookID>/', acc_request_book, name='acc_request_book'),
    path('delete-request-book/<int:bookID>/', delete_request_book, name='delete_request_book'),
    path('request_book_details/', request_book_details, name='request_book_details'),
    path('get-request-books/', get_request_books_json, name='get_request_books_json'),
    

    path('make-book/', make_buku, name='make_book'),
    path('search/', search_books, name='search'),
    path('book_details/', book_details, name='book_details'),
    path('sort/<str:query>', sort_books, name='sort'),

    path('create-book/', create_book, name='create_book'),
    path('edit-book/<int:bookID>/', edit_book, name='edit_book'),
    path('delete-book/<int:bookID>/', delete_book, name='delete_book'),
    
    path('create-book-flutter/', create_book_flutter, name='create_book_flutter'),
    path('edit-book-flutter/', edit_book_flutter, name='edit_book_flutter'),
    path('delete-book-flutter/', delete_book_flutter, name='delete_book_flutter'),
    path('acc-request-book-flutter/', acc_request_book_flutter, name='acc_request_book_flutter'),
    path('delete-request-book-flutter/', delete_request_book_flutter, name='delete_request_book_flutter'),

    path('get-books/', get_books_json, name='get_books_json'),
    path('get_user/', get_user, name='get_user'),
    path('get_buku_by_author/', get_buku_by_author, name='get_buku_by_author'),
]

authentication_bookmark/urls.py
from django.urls import path
from authentication_bookmark.views import show_bookmark
from authentication_bookmark.views import register, get_bookmark_user
from authentication_bookmark.views import login_user, login_flutter, logout_flutter, register_flutter
from authentication_bookmark.views import logout_user, delete_bookmark , add_bookmark_ajax, get_bookmark_json, show_json
from daftar_buku.views import show_main

app_name = 'authentication_bookmark'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('bookmark/', show_bookmark, name='show_bookmark'),
    path('register/', register, name='register'), 
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('delete/<int:id>', delete_bookmark, name='delete_bookmark'),
    path('get-bookmark/', get_bookmark_json, name='get_bookmark_json'),
    path('add-bookmark-ajax/', add_bookmark_ajax, name='add_bookmark_ajax'),
    path('json/', show_json, name='show_json'), 
    path('login-flutter/', login_flutter, name='login'),
    path('logout-flutter/', logout_flutter, name='logout'),
    path('register-flutter/', register_flutter, name = 'register'),
    path('get_bookmark_user/', get_bookmark_user, name='get_bookmark_user'),
]

daftar_buku/urls.py
from django.urls import path
from daftar_buku.views import show_main, make_buku, book_details, search_books, sort_books, show_xml, get_books_json, get_user, get_buku_by_author, create_request_book, get_buku_search, sort_books_json,\
sort_books_json, get_rating


app_name = 'daftar_buku'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('make-book/', make_buku, name='make_book'),
    path('book_details/', book_details, name='book_details'),
    path('search/', search_books, name='search'),
    path('sort/<str:query>', sort_books, name='sort'),
    path('xml/<int:id>/', show_xml, name='show_xml'),
    path('get_books_json/', get_books_json, name='get_books_json'),
    path('get_user/', get_user, name='get_user'),
    path('get_buku_by_author/', get_buku_by_author, name='get_buku_by_author'),
    path('create-request-book/', create_request_book, name='create_request_book'),
    path('searchjson/', get_buku_search, name='get_buku_search'),
    path('sortjson/<str:query>', sort_books_json, name='sort_books_json'),
    path('get_rating/', get_rating, name='get_rating'),
    
]

pinjam_buku/urls.py
from django.urls import path
from pinjam_buku.views import pinjam_buku_outer, lihatbukudipinjam, get_peminjaman_json, get_peminjaman_json_by_id, pengembalian_by_ajax, show_pengembalian

app_name = 'pinjam_buku'

urlpatterns = [
    path('details/<int:id>/', pinjam_buku_outer, name='pinjam_buku'),
    path('borrowed/', lihatbukudipinjam, name="list_pinjam"),
    path('peminjamanjson/', get_peminjaman_json, name="get_peminjaman_json"),
    path('peminjamanjsonbyid/<int:id>', get_peminjaman_json_by_id, name="get_peminjaman_json_by_id"),
    path('pengembalianbyajax', pengembalian_by_ajax, name="pengembalian_ajax"),
    path('returned/', show_pengembalian, name="show_pengembalian"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {% block meta %}
        {% endblock meta %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
            crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
        
   

    </head>
    <body data-csrf-token="{{ csrf_token }}">
        {% block content %}
        {% endblock content %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
    </body>
</html>

templates/navbaradmin.html
<header data-bs-theme="light">
    <nav class="navbar navbar-expand-md fixed-top bg-light" id="navbar-1">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'admin_buku:show_main' %}">
                <img src="https://raw.githubusercontent.com/PBP-D-11-2023/Wisdom-Repository/anisha/assets/images/wr%20logo.png"
                    alt="Logo" width="156" height="52" class="d-inline-block align-text-top">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarCollapse">
                <ul class="nav justify-content-end me-3">
                    <li class="nav-item me-2">
                        <a class="nav-link active text-dark" href="{% url 'admin_buku:request_book' %}">Request</a>
                    </li>
                    <li class="nav-item me-2">
                        <a class="nav-link active text-dark" href="{% url 'authentication_bookmark:logout' %}">Log
                            Out</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

templates/navbaruser.html
{% load static %}
<header data-bs-theme="light">
    <nav class="navbar navbar-expand-md fixed-top bg-light" id="navbar-1">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'daftar_buku:show_main' %}">
                <img src="{% static 'pinjam_buku/img/logo.png' %}"
                    alt="Logo" width="156" height="52" class="d-inline-block align-text-top">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarCollapse">
                <ul class="nav justify-content-end me-3">
                    <li class="nav-item me-2">
                        <a class="nav-link active text-dark"
                            href="{% url 'authentication_bookmark:show_bookmark' %}">Bookmark</a>
                    </li>
                    <li class="nav-item me-2">
                        <a class="nav-link active text-dark"
                            href="{% url 'pinjam_buku:show_pengembalian' %}">Returned</a>
                    </li>
                    <li class="nav-item me-2">
                        <a class="nav-link active text-dark" href="{% url 'pinjam_buku:list_pinjam' %}">Borrowed</a>
                    </li>
                    <li class="nav-item me-2">
                        <a class="nav-link active text-dark" href="{% url 'authentication_bookmark:logout' %}">Log Out</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>