Wisdom_Repository/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin-buku/', include('admin_buku.urls')),
    path('main/', include('daftar_buku.urls')),
    path('', include('authentication_bookmark.urls')),
    path('borrow/', include('pinjam_buku.urls')),
    path('review/', include('review_buku.urls')),
]

admin_buku/urls.py
from django.urls import path
from admin_buku.views import show_main, make_buku, search_books, sort_books, delete_book, request_buku, delete_request_book, get_request_books_json
from admin_buku.views import get_books_json, get_user, get_buku_by_author, book_details, create_book, edit_book, acc_request_book, request_book_details
from admin_buku.views import create_book_flutter, edit_book_flutter, delete_book_flutter, acc_request_book_flutter, delete_request_book_flutter

app_name = 'admin_buku'

urlpatterns = [
    path('', show_main, name='show_main'),

    path('request-book/', request_buku, name='request_book'),
    path('acc-request-book/<int:bookID>/', acc_request_book, name='acc_request_book'),
    path('delete-request-book/<int:bookID>/', delete_request_book, name='delete_request_book'),
    path('request_book_details/', request_book_details, name='request_book_details'),
    path('get-request-books/', get_request_books_json, name='get_request_books_json'),
    

    path('make-book/', make_buku, name='make_book'),
    path('search/', search_books, name='search'),
    path('book_details/', book_details, name='book_details'),
    path('sort/<str:query>', sort_books, name='sort'),

    path('create-book/', create_book, name='create_book'),
    path('edit-book/<int:bookID>/', edit_book, name='edit_book'),
    path('delete-book/<int:bookID>/', delete_book, name='delete_book'),
    
    path('create-book-flutter/', create_book_flutter, name='create_book_flutter'),
    path('edit-book-flutter/', edit_book_flutter, name='edit_book_flutter'),
    path('delete-book-flutter/', delete_book_flutter, name='delete_book_flutter'),
    path('acc-request-book-flutter/', acc_request_book_flutter, name='acc_request_book_flutter'),
    path('delete-request-book-flutter/', delete_request_book_flutter, name='delete_request_book_flutter'),

    path('get-books/', get_books_json, name='get_books_json'),
    path('get_user/', get_user, name='get_user'),
    path('get_buku_by_author/', get_buku_by_author, name='get_buku_by_author'),
]

daftar_buku/urls.py
from django.urls import path
from daftar_buku.views import show_main, make_buku, book_details, search_books, sort_books, show_xml, get_books_json, get_user, get_buku_by_author, create_request_book, get_buku_search, sort_books_json,\
sort_books_json, get_rating


app_name = 'daftar_buku'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('make-book/', make_buku, name='make_book'),
    path('book_details/', book_details, name='book_details'),
    path('search/', search_books, name='search'),
    path('sort/<str:query>', sort_books, name='sort'),
    path('xml/<int:id>/', show_xml, name='show_xml'),
    path('get_books_json/', get_books_json, name='get_books_json'),
    path('get_user/', get_user, name='get_user'),
    path('get_buku_by_author/', get_buku_by_author, name='get_buku_by_author'),
    path('create-request-book/', create_request_book, name='create_request_book'),
    path('searchjson/', get_buku_search, name='get_buku_search'),
    path('sortjson/<str:query>', sort_books_json, name='sort_books_json'),
    path('get_rating/', get_rating, name='get_rating'),
    
]

pinjam_buku/urls.py
from django.urls import path
from pinjam_buku.views import pinjam_buku_outer, lihatbukudipinjam, get_peminjaman_json, get_peminjaman_json_by_id, pengembalian_by_ajax, show_pengembalian

app_name = 'pinjam_buku'

urlpatterns = [
    path('details/<int:id>/', pinjam_buku_outer, name='pinjam_buku'),
    path('borrowed/', lihatbukudipinjam, name="list_pinjam"),
    path('peminjamanjson/', get_peminjaman_json, name="get_peminjaman_json"),
    path('peminjamanjsonbyid/<int:id>', get_peminjaman_json_by_id, name="get_peminjaman_json_by_id"),
    path('pengembalianbyajax', pengembalian_by_ajax, name="pengembalian_ajax"),
    path('returned/', show_pengembalian, name="show_pengembalian"),
]

review_buku/urls.py
from django.urls import path
from . import views
app_name = "review_buku"

urlpatterns = [
    path('review/<int:id>/', views.review, name='review'),  # Tambahkan id sebagai parameter
    path('show/<int:id>/', views.show_reviews, name='show_reviews'),  # Tambahkan id sebagai parameter
    path('post_review/', views.post_review, name='post_review'),
]

pinjam_buku/models.py
import datetime
from django.db import models
from django.db.models import F
from authentication_bookmark.models import CustomUser
from daftar_buku.models import Buku

# Create your models here.
class Peminjaman(models.Model):
    buku = models.ForeignKey(Buku, on_delete=models.CASCADE)
    peminjam = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    idBuku = models.IntegerField()
    tanggal_dipinjam = models.DateField(auto_now_add=True)
    hari = models.IntegerField(null=True, blank=True)
    tanggal_pengembalian = models.DateField(null=True, blank=True)
    def save(self, *args, **kwargs):
        self.tanggal_dipinjam = datetime.datetime.now().date()
        if not self.hari:
            if self.peminjam.member.lower() == "premium":
                self.hari = 7
            else:
                self.hari = 3
        if not self.tanggal_pengembalian:
            self.tanggal_pengembalian = self.tanggal_dipinjam + datetime.timedelta(days=self.hari)
        super(Peminjaman, self).save(*args, **kwargs)

class Pengembalian(models.Model):
    buku = models.ForeignKey(Buku, on_delete=models.CASCADE)
    peminjam = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    idBuku = models.IntegerField()
    review = models.BooleanField(default=False)

pinjam_buku/forms.py
from django.forms import ModelForm
from pinjam_buku.models import Peminjaman

class PeminjamanForm(ModelForm):
    class Meta:
        model = Peminjaman
        fields = ["idBuku"]

pinjam_buku/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound, JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from django.urls import reverse
from django.contrib import messages
from daftar_buku.models import Buku
from pinjam_buku.models import Peminjaman, Pengembalian
from pinjam_buku.forms import PeminjamanForm
import datetime

# Create your views here.
@login_required(login_url='/login')
def pinjam_buku_outer(request, id):
    buku = Buku.objects.filter(pk=id).first()
    form = PeminjamanForm(request.POST or None, initial={'idBuku': id})
    username = request.user.username
    member = request.user.member
    if member.lower() == "premium":
        hari = 7
    else:
        hari = 3
    hari_kembali = (datetime.datetime.now() + datetime.timedelta(days=hari)).date()
    context = {
        'buku': buku,
        'username': username,
        'member': member,
        'return': hari_kembali,
        'form': form,
    }
    #print(form.is_valid())
    if form.is_valid() and request.method == "POST":
        check = Peminjaman.objects.filter(buku = buku, peminjam=request.user)
        if len(check) != 0:
            messages.warning(request, 'Buku sudah anda pinjam saat ini.')
            return redirect('pinjam_buku:list_pinjam')
        check = Peminjaman.objects.filter(buku = buku)
        if len(check) != 0:
            messages.warning(request, 'Buku sedang dipinjam oleh member lain. Silahkan kembali beberapa saat nanti.')
            return redirect('pinjam_buku:list_pinjam')
        check = Peminjaman.objects.filter(peminjam=request.user)
        if (request.user.member.lower() == "premium"):
            batas = 7
        else:
            batas = 3
        if len(check) >= batas:
            messages.warning(request, 'Batas peminjaman buku sudah tercapai. Silahkan kembalikan beberapa buku yang sudah dipinjam sebelumnya.')
            return redirect('pinjam_buku:list_pinjam')
        peminjaman = form.save(commit=False)
        peminjaman.peminjam = request.user
        peminjaman.buku = buku
        peminjaman.save()
        #print(Peminjaman.objects.all())
        messages.success(request, 'Buku berhasil dipinjam')
        return redirect('pinjam_buku:list_pinjam')
    return render(request, "pinjambuku.html", context)

@login_required(login_url='/login')
def lihatbukudipinjam(request):
    peminjamans = Peminjaman.objects.filter(peminjam = request.user)
    context = {
        'peminjamans': peminjamans
    }
    return render(request, "listbukudipinjam.html", context)

@login_required(login_url='/login')
def get_peminjaman_json(request):
    peminjamans = Peminjaman.objects.filter(peminjam = request.user).values('pk', 'idBuku', 'buku__gambar', 'buku__judul', 'tanggal_dipinjam', 'tanggal_pengembalian')
    peminjaman_list = list(peminjamans)
    return JsonResponse(peminjaman_list, safe=False)

@login_required(login_url='/login')
def get_peminjaman_json_by_id(request, id):
    peminjamans = Peminjaman.objects.filter(pk = id).values('pk', 'idBuku', 'buku__gambar', 'buku__judul', 'peminjam__username', 'peminjam__member', 'tanggal_dipinjam', 'tanggal_pengembalian')
    peminjaman_list = list(peminjamans)
    return JsonResponse(peminjaman_list, safe=False)

@login_required(login_url='/login')
@csrf_exempt
def pengembalian_by_ajax(request):
    if request.method == 'POST':
        id_peminjaman = request.POST.get("idPeminjaman")
        id_buku = request.POST.get("idbuku")
        peminjaman = Peminjaman.objects.filter(pk = id_peminjaman, peminjam=request.user).first()
        peminjaman.delete()
        user = request.user
        buku_dikembalikan = Buku.objects.filter(pk = id_buku).first()
        check_pengembalian = Pengembalian.objects.filter(buku = buku_dikembalikan, peminjam=user)
        if len(check_pengembalian) == 0:
            new_pengembalian = Pengembalian(buku = buku_dikembalikan, peminjam = user, idBuku = id_buku, review = False)
            new_pengembalian.save()
            return HttpResponse(b"CREATED", status=201)
        return HttpResponse(b"DELETED PEMINJAMAN", status=201)
    return HttpResponseNotFound()

@login_required(login_url='/login')
def show_pengembalian(request):
    pengembalians = Pengembalian.objects.filter(peminjam = request.user, review = False)
    context = {
        'pengembalians': pengembalians
    }
    return render(request, "listbukureturn.html", context)

pinjam_buku/templates/listbukudipinjam.html
{% extends 'base.html' %}

{% block content %}
    <title>List Buku Dipinjam</title>
    {% include 'navbaruser.html' %}
    {% load static %}
	<div class="container-fluid">
        <div class="row">
            <div class="bg-image top-section">
                <p class="text-margin-first">Borrowed Books</p>
            </div>
            <div class="col md-0 bottom-left-section">
                <div class="container-aturan">
                    <p class="hurufrules">Rules</p>
                    <p>
                        1. Buku yang dipinjam harus dikembalikan sebelum tanggal pengembalian.
                    </p>
                    <p>
                        2. Member premium maksimal memiliki 7 peminjaman buku, member reguler maksimal memiliki 3 peminjaman buku dalam satu waktu bersamaan.
                    </p>
                    <p>
                        3. Jika buku yang mau dipinjam tidak ada list di sini, berarti batas maksimal peminjaman sudah tercapai atau buku sedang dipinjam member lain.
                    </p>
                </div>
                {% if messages %}
                <div>
                    <p style="font-size:40px">INFO</p>
                    {% for message in messages %}
                    <p>{{ message }}</p>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div id="daftarpeminjaman" class="col-md-0 bottom-right-section">
                {% if peminjamans %}
                <div class="row">
                    {% for peminjaman in peminjamans %}
                    <div class="col-lg-6 col-md-6 col-sm-12 mb-4">
                        <div class="card">
                            <img src="{{peminjaman.buku.gambar}}" class="card-img" alt="{{peminjaman.buku.judul}}">
                            <div class="card-body">
                                <h5 class="card-title judultext"><u>{{peminjaman.buku.judul}}</u></h5>
                                <p class="card-text">Tanggal dipinjam:</p>
                                <p class="card-text">{{peminjaman.tanggal_dipinjam}}</p>
                                <p class="card-text">Tanggal dikembalikan:</p>
                                <p class="card-text">{{peminjaman.tanggal_pengembalian}}</p>
                                <button type="button" class="button-return" data-bs-toggle="modal" data-bs-target="#modalPengembalian" data-id="{{peminjaman.pk}}">Return</button>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% else %}
                <div class="row">
                <p>Belum ada buku yang dipinjam saat ini</p>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="modal fade" id="modalPengembalian" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="modalLabel">Konfirmasi Pengembalian</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="username" class="col-form-label">Username</label>
                            <input type="text" class="form-control" id="username" name="username" readonly>
                        </div>
                        <div class="mb-3">
                            <label for="tipemember" class="col-form-label">Tipe Member:</label>
                            <input type="text" class="form-control" id="tipemember" name="tipemember" readonly>
                        </div>
                        <div class="mb-3">
                            <label for="book" class="col-form-label">Judul Buku:</label>
                            <input type="text" class="form-control" id="book" name="book" readonly>
                        </div>
                        <div class="mb-3">
                            <label for="return" class="col-form-label">Tanggal Pengembalian:</label>
                            <input type="text" class="form-control" id="return" name="return" readonly>
                        </div>
                        <div class="mb-3" style="display: none;">
                            <input type="text" class="form-control" id="idPeminjaman" name="idPeminjaman" readonly>
                        </div>
                        <div class="mb-3" style="display: none;">
                            <input type="text" class="form-control" id="idbuku" name="idbuku" readonly>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Tutup</button>
                    <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Konfirmasi</button>
                </div>
            </div>
        </div>
    </div>
    <script>
        async function getPeminjaman() {
            return fetch("{% url 'pinjam_buku:get_peminjaman_json' %}").then((res) => res.json())
        }
        async function getPeminjamanByID(id) {
            const url = `{% url 'pinjam_buku:get_peminjaman_json_by_id' id=1 %}`.replace('1', id);
            return fetch(url).then((res) => res.json())
        }

        function addButtonListener() {
            const returnButtons1 = document.getElementsByClassName("button-return");
            const returnButtons = Array.from(returnButtons1);
            returnButtons.forEach(button => {
                button.addEventListener('click', function (event) {
                    const id = parseInt(event.target.dataset.id);
                    refreshIsiModal(id);
                });
            });
        }
        async function refreshIsiModal(id) {
            const isiModal = await getPeminjamanByID(id);
            const isiModalSatuan = isiModal[0];
            document.getElementById("username").value = isiModalSatuan.peminjam__username;
            document.getElementById("tipemember").value = isiModalSatuan.peminjam__member;
            document.getElementById("book").value = isiModalSatuan.buku__judul;
            document.getElementById("return").value = isiModalSatuan.tanggal_pengembalian;
            document.getElementById("idPeminjaman").value = isiModalSatuan.pk;
            document.getElementById("idbuku").value = isiModalSatuan.idBuku;
        }
        async function refreshPeminjaman() {
            document.getElementById("daftarpeminjaman").innerHTML = ""
            const peminjamans = await getPeminjaman()
            let htmlString = `<div class="row">`
            if (peminjamans.length == 0) {
                htmlString += `<p>Belum ada buku yang dipinjam saat ini</p>`
            }
            else {
                peminjamans.forEach((peminjaman) => {
                    htmlString += `<div class="col-lg-6 col-md-6 col-sm-12 mb-4">
                        <div class="card">
                            <img src="${peminjaman.buku__gambar}" class="card-img" alt="Image 1">
                            <div class="card-body">
                                <h5 class="card-title judultext"><u>${peminjaman.buku__judul}</u></h5>
                                <p class="card-text">Tanggal dipinjam:</p>
                                <p class="card-text">${peminjaman.tanggal_dipinjam}</p>
                                <p class="card-text">Tanggal dikembalikan:</p>
                                <p class="card-text">${peminjaman.tanggal_pengembalian}</p>
                                <button type="button" class="button-return" data-bs-toggle="modal" data-bs-target="#modalPengembalian" data-id="${peminjaman.pk}">Return</button>
                            </div>
                        </div>
                    </div>`
                })
            }
            htmlString += `</div>`
            document.getElementById("daftarpeminjaman").innerHTML = htmlString
            addButtonListener()
        }
        refreshPeminjaman()
        function addPengembalian() {
            fetch("{% url 'pinjam_buku:pengembalian_ajax' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(refreshPeminjaman)

            document.getElementById("form").reset()
            const userConfirmed = confirm('Apakah anda mau mereview buku yang sudah dikembalikan?');
            if (userConfirmed) {
                window.location.href = "{% url 'pinjam_buku:show_pengembalian' %}";
            }
            return false
        }
        document.getElementById("button_add").onclick = addPengembalian
    </script>
    <style>
        body {
            font-size: 16px;
            font-family: "Book Antiqua";
            background-color: #F5F2ED;
            font-weight: bold;
        }
    
        .top-section {
            background-image: url("{% static 'pinjam_buku/img/bookmark.png' %}");
            background-size: cover;
            background-position: center;
            width: 100vw;
            height: 30vh;
            color: #37465D;
            position: relative;
            z-index: 2;
        }
    
        .bottom-left-section {
            padding: 20px;
            height: 70vh;
            margin-left: 2vw;
            max-width: 30vw;
            z-index: 1;
        }
    
        .bottom-right-section {
            padding: 20px;
            height: 70vh;
            margin-left: 30vw;
            max-width: 70vw;
            z-index: 1;
            margin-top: -70vh
        }
    
        .border-image {
            border: 1vh solid white;
        }
    
        .text-margin-first {
            margin-left: 38vw;
            margin-top: 17vh;
            font-size: 36px;
            position: relative;
        }
    
        .button-return {
            background-color: #37465D;
            color: white;
            padding: 10px 20px;
            border: 1px solid white;
            cursor: pointer;
            font-size: 18px;
        }
    
        .small-card {
            width: 30vw;
            height: 30vh;
            transition: transform 0.2s;
            background-color: rgb(255, 255, 255);
            color: black;
            margin-top: 15px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
            text-align: center;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }
    
        .small-card .card {
            height: 100%;
            margin-top: 0;
            padding: 0;
    
        }
    
        .small-card .card-img {
            margin-top: 15px;
            max-width: 40%;
            object-fit: contain;
            height: 90%;
            margin-right: auto;
            margin-left: 10%;
        }
    
        .small-card .card-body {
            height: 25%;
        }
    
        .container-aturan {
            background-color: #37465D;
            color: white;
            padding: 20px;
            width: 25vw;
            height: 100vh;
            border-radius: 1vh;
        }
    
        .hurufrules {
            font-size: 40px;
            text-decoration-line: underline;
        }
    
        .card {
            display: flex;
        }
    
        .judultext {
            font-size: 30px;
        }
    
        @media (max-width: 767px) {
            .card {
                flex-direction: column;
                align-items: center;
                text-align: center;
            }
    
            .card .card-img {
                margin-top: 5%;
                margin-bottom: 5%;
                max-width: 40%;
                object-fit: contain;
                height: 50%;
                margin-right: 5%;
                margin-left: 5%;
            }
        }
    
        @media (min-width: 768px) {
            .card {
                flex-direction: row;
            }
    
            .card .card-img {
                margin-top: 5%;
                margin-bottom: 5%;
                max-width: 40%;
                object-fit: contain;
                height: 50%;
                margin-right: 5%;
                margin-left: 5%;
            }
        }
    </style>
{% endblock content %}

pinjam_buku/templates/listbukureturn.html
{% extends 'base.html' %}

{% block content %}
    <title>List Buku Dikembalikan</title>
    {% include 'navbaruser.html' %}
    {% load static %}
	<div class="container-fluid">
        <div class="row">
            <div class="bg-image top-section">
                <p class="text-margin-first"><strong>Returned Books</strong></p>
            </div>
            <div>
                <p class="margin-judul"><u>List of Books</u></p>
            </div>
            <div class="col-md-0 bottom-right-section">
                {% if pengembalians %}
                <div class="row">
                    {% for pengembalian in pengembalians %}
                    <div class="col-md-2 col-sm-3 col-4">
                        <div class="card small-card">
                            <img src="{{ pengembalian.buku.gambar }}" class="card-img" alt="{{ pengembalian.buku.judul }}"
                                data-toggle="modal" data-target="#bookModal" data-id="{{ pengembalian.buku.idBuku }}">
                            <div class="card-body d-flex flex-column">
                                <h5 class="card-title" id="judul-card"
                                    style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; font-size: 14px;"
                                    title="{{ pengembalian.buku.judul }}"><strong>{{ pengembalian.buku.judul }}</strong></h5>
                            </div>
							<a href="{% url 'review_buku:review' pengembalian.idBuku %}">
                                <button type="button" class="button-review"><strong>Review</strong></button>
                            </a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% else %}
                <p>Belum ada buku yang dikembalikan dan belum direview</p>
                {% endif %}
            </div>
        </div>
    </div>
    <style>
        body {
            font-size: 16px;
            font-family: "Book Antiqua";
            background-color: #F5F2ED;
            font-weight: bold;
        }
    
        .top-section {
            background-image: url("{% static 'pinjam_buku/img/bookmark.png' %}");
            background-size: cover;
            background-position: center;
            width: 100vw;
            height: 30vh;
            color: #37465D;
            position: relative;
            z-index: 2;
        }
    
        .bottom-left-section {
            padding: 20px;
            height: 70vh;
            margin-left: 2vw;
            max-width: 30vw;
            z-index: 1;
        }
    
        .bottom-right-section {
            padding: 20px;
            height: 70vh;
            margin-left: 5vw;
            max-width: 90vw;
            z-index: 1;
        }
    
        .border-image {
            border: 1vh solid white;
        }
    
        .text-margin-first {
            margin-left: 38vw;
            margin-top: 17vh;
            font-size: 36px;
            position: relative;
        }
    
        .button-review {
            background-color: #37465D;
            color: white;
            padding: 10px 20px;
            border: 1px solid black;
            cursor: pointer;
            margin-left: auto;
            margin-bottom: 5%;
        }
    
        .small-card {
            max-width: 10rem;
            height: 16rem;
            transition: transform 0.2s;
            background-color: rgb(255, 255, 255);
            color: black;
            margin-top: 15px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
            text-align: center;
            width: 100%;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }
    
        .small-card .card {
            height: 100%;
            margin-top: 0;
            padding: 0;
    
        }
    
        .small-card .card-img {
            margin-top: 15px;
            max-width: 100px;
            object-fit: contain;
            height: 50%;
            margin-right: auto;
            margin-left: auto;
        }
    
        .small-card .card-body {
            height: 25%;
        }
    
        .margin-judul {
            font-size: 30px;
            margin-left: 5vw;
            margin-top: 2vh;
        }
    </style>
{% endblock content %}